import { createReadStream, createWriteStream } from 'node:fs';
import { mkdir, rm, stat } from 'node:fs/promises';
import { dirname, resolve, sep } from 'node:path';
import type { Readable, Writable } from 'node:stream';

/**
 * Storage for generated files (privacy exports). Local disk today; an S3 implementation with the
 * same interface is part of production readiness. Keys are generated by the API, never by users,
 * and are still checked so they cannot escape the base directory.
 */
export interface FileStore {
  writer(key: string): Promise<Writable>;
  reader(key: string): Readable;
  size(key: string): Promise<number>;
  remove(key: string): Promise<void>;
}

export class LocalFileStore implements FileStore {
  private readonly base: string;

  constructor(baseDir: string) {
    this.base = resolve(baseDir);
  }

  private path(key: string): string {
    const full = resolve(this.base, key);
    if (!full.startsWith(this.base + sep)) throw new Error('Invalid file key');
    return full;
  }

  async writer(key: string): Promise<Writable> {
    const full = this.path(key);
    await mkdir(dirname(full), { recursive: true });
    return createWriteStream(full, { mode: 0o600 });
  }

  reader(key: string): Readable {
    return createReadStream(this.path(key));
  }

  async size(key: string): Promise<number> {
    return (await stat(this.path(key))).size;
  }

  async remove(key: string): Promise<void> {
    await rm(this.path(key), { force: true });
  }
}
