import { Router } from 'express';
import { createAdvertisersRouter } from './modules/advertisers/advertisers.routes';
import { createAnalyticsRouter } from './modules/analytics/analytics.routes';
import { createAuditRouter } from './modules/audit/audit.routes';
import { createAuthRouter } from './modules/auth/auth.routes';
import { createCampaignsRouter } from './modules/campaigns/campaigns.routes';
import { createConversionsRouter } from './modules/conversions/conversions.routes';
import { createDomainsRouter } from './modules/domains/domains.routes';
import { createFinanceRouter } from './modules/finance/finance.routes';
import { createFraudRouter } from './modules/fraud/fraud.routes';
import { createLinksRouter } from './modules/links/links.routes';
import { createNotificationsRouter } from './modules/notifications/notifications.routes';
import { createOrganizationsRouter } from './modules/organizations/organizations.routes';
import { createPostbacksRouter } from './modules/postbacks/postbacks.routes';
import { createPrivacyRouter } from './modules/privacy/privacy.routes';
import { createPublishersRouter } from './modules/publishers/publishers.routes';
import { createScheduledReportsRouter } from './modules/scheduled-reports/scheduled-reports.routes';
import { createSearchRouter } from './modules/search/search.routes';
import { createRolesRouter } from './modules/roles/roles.routes';
import { createToolsRouter } from './modules/tools/tools.routes';
import { createTravelRouter } from './modules/travel/travel.routes';
import { createTrafficSourcesRouter } from './modules/traffic-sources/traffic-sources.routes';
import { createUsersRouter } from './modules/users/users.routes';
import type { AppDeps } from './types';

/** Registry of every v1 module router. */
export const createV1Router = (deps: AppDeps) => {
  const router = Router();
  router.use('/auth', createAuthRouter(deps));
  router.use('/organizations', createOrganizationsRouter(deps));
  router.use('/roles', createRolesRouter(deps));
  router.use('/users', createUsersRouter(deps));
  router.use('/audit-logs', createAuditRouter(deps));
  router.use('/advertisers', createAdvertisersRouter(deps));
  router.use('/publishers', createPublishersRouter(deps));
  router.use('/traffic-sources', createTrafficSourcesRouter(deps));
  router.use('/campaigns', createCampaignsRouter(deps));
  router.use('/domains', createDomainsRouter(deps));
  router.use('/links', createLinksRouter(deps));
  router.use('/conversions', createConversionsRouter(deps));
  router.use('/postbacks', createPostbacksRouter(deps));
  router.use('/finance', createFinanceRouter(deps));
  router.use('/fraud', createFraudRouter(deps));
  router.use('/search', createSearchRouter(deps));
  router.use('/travel', createTravelRouter(deps));
  router.use('/notifications', createNotificationsRouter(deps));
  router.use('/privacy', createPrivacyRouter(deps));
  router.use('/analytics', createAnalyticsRouter(deps));
  router.use('/scheduled-reports', createScheduledReportsRouter(deps));
  router.use('/tools', createToolsRouter(deps));
  return router;
};
